#!/usr/bin/env python3
"""Prepare AmigaDOS differential-compatibility command files.

This tool does not claim runtime qualification. It converts the canonical
compatibility corpus into guest-side scripts for the native Shell reference
and the AmShell candidate path. Guest output/RC files are collected and then
compared by compat_compare.py.
"""

from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES = ROOT / "tests" / "compat" / "cases.txt"


def load_cases(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def q(text: str) -> str:
    """Quote a string for an AmigaDOS command argument."""
    return '"' + text.replace('"', '*"') + '"'


def write_case_files(out: Path, cases: list[str]) -> None:
    case_dir = out / "cases"
    case_dir.mkdir(parents=True, exist_ok=True)
    for number, command in enumerate(cases, start=1):
        case_id = f"{number:03d}"
        (case_dir / f"native-{case_id}.script").write_text(
            command + "\n", encoding="utf-8", newline="\n"
        )


def write_runner(
    path: Path, cases: list[str], mode: str, amshell: str, native_launcher: str
) -> None:
    lines = [
        "; generated by tools/compat_prepare.py",
        "FailAt 20",
        "MakeDir T:AmShellCompat >NIL:",
    ]

    for number, command in enumerate(cases, start=1):
        case_id = f"{number:03d}"
        out = f"T:AmShellCompat/{mode}-{case_id}.out"
        rc = f"T:AmShellCompat/{mode}-{case_id}.rc"

        if mode == "native":
            # The launcher reads the exact one-line command file and delegates
            # it opaquely to the native Shell with an explicit output handle.
            # This avoids Execute's non-redirectable script output on V40 and
            # earlier without adding capture syntax to the tested command.
            lines.append(
                f"{native_launcher} cases/native-{case_id}.script {out}"
            )
        else:
            # Candidate command text is passed as one -c argument. The outer
            # capture belongs to the harness, while any redirection inside
            # command remains part of the tested command text.
            lines.append(f"{amshell} -c {q(command)} >{out}")
        lines.append(f"Echo $RC >{rc}")

    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cases", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--out", type=Path, default=ROOT / "build" / "compat")
    parser.add_argument("--amshell", default="AmShell")
    parser.add_argument("--native-launcher", default="CompatNative")
    args = parser.parse_args()

    cases = load_cases(args.cases)
    if not cases:
        raise SystemExit("compatibility corpus is empty")

    args.out.mkdir(parents=True, exist_ok=True)
    write_case_files(args.out, cases)
    write_runner(
        args.out / "run-native.script",
        cases,
        "native",
        args.amshell,
        args.native_launcher,
    )
    write_runner(
        args.out / "run-amshell.script",
        cases,
        "amshell",
        args.amshell,
        args.native_launcher,
    )
    (args.out / "manifest.txt").write_text(
        "".join(f"{i:03d}\t{command}\n" for i, command in enumerate(cases, 1)),
        encoding="utf-8",
    )

    print(f"Prepared {len(cases)} compatibility cases in {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
