#!/usr/bin/env python3
"""Prepare AmigaDOS differential-compatibility command files.

This tool does not claim runtime qualification.  It converts the canonical
compatibility corpus into two AmigaDOS scripts: one invoking the native Shell
path directly and one invoking AmShell -c.  Guest-side output/RC files are
then collected and compared by compat_compare.py.
"""

from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CASES = ROOT / "tests" / "compat" / "cases.txt"


def load_cases(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def q(text: str) -> str:
    """Quote a string for an AmigaDOS command argument."""
    return '"' + text.replace('"', '*"') + '"'


def write_script(path: Path, cases: list[str], mode: str, amshell: str) -> None:
    lines = [
        "; generated by tools/compat_prepare.py",
        "FailAt 20",
        "MakeDir T:AmShellCompat >NIL: 2>NIL:",
    ]

    for number, command in enumerate(cases, start=1):
        case_id = f"{number:03d}"
        out = f"T:AmShellCompat/{mode}-{case_id}.out"
        rc = f"T:AmShellCompat/{mode}-{case_id}.rc"

        # The command is passed as one argument to AmShell for the candidate
        # path.  Native reference text is executed directly by the Shell.
        if mode == "native":
            lines.append(f"{command} >{out}")
        else:
            lines.append(f"{amshell} -c {q(command)} >{out}")
        lines.append(f"Echo $RC >{rc}")

    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cases", type=Path, default=DEFAULT_CASES)
    parser.add_argument("--out", type=Path, default=ROOT / "build" / "compat")
    parser.add_argument("--amshell", default="AmShell")
    args = parser.parse_args()

    cases = load_cases(args.cases)
    if not cases:
        raise SystemExit("compatibility corpus is empty")

    args.out.mkdir(parents=True, exist_ok=True)
    write_script(args.out / "run-native.script", cases, "native", args.amshell)
    write_script(args.out / "run-amshell.script", cases, "amshell", args.amshell)
    (args.out / "manifest.txt").write_text(
        "".join(f"{i:03d}\t{command}\n" for i, command in enumerate(cases, 1)),
        encoding="utf-8",
    )

    print(f"Prepared {len(cases)} compatibility cases in {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
